name: Blue_pill_01 - tests CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '10.3-2021.10'

    - name: Configure, build tests
      working-directory: ./blue_pill_01
      run: |
        cmake -B build_test -DBUILD_LIB_TESTS=ON .
        cmake --build build_test

    - name: Run tests
      working-directory: ./blue_pill_01/build_test
      run: ctest --output-on-failure
